replicaCount: 1

image:
  repository: hub.opensciencegrid.org/pelican_platform/cache
  tag: latest
  pullPolicy: IfNotPresent

service:
  ports:
    xrootd: 8443
    webui: 8000
    xrootdNodePort: 31812 # OpenShift ignores :_(

pelicanEnv:
  PELICAN_XROOTD_PORT: "8443"
  #KUBERNETES_PORT: "tcp://172.25.128.1:443"

resources: {}
# resources:
#   requests:
#     cpu: 100m
#     memory: 128Mi
#   limits:
#     cpu: 1
#     memory: 1Gi

# OpenShift friendly: don't force runAsUser; let SCC decide.
podSecurityContext: {}
securityContext: {}

# annotations for the cache deployment
annotations:
    ccs.ornl.gov/fs: orion

# Optional: create OpenShift Route for 8443 (edge-terminated by default)
route:
  enabled: true
  termination: reencrypt
  host: pelican-lrn045.apps.marble.ccs.ornl.gov
