apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pelican-cache.fullname" . }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  labels:
    {{- include "pelican-cache.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pelican-cache.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pelican-cache.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      enableServiceLinks: false  # Disables automatic env-var injection
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: pelican-cache
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- if .Values.pelicanEnv }}
          env:
          {{- range $k, $v := .Values.pelicanEnv }}
          - name: "{{ $k }}"
            value: "{{ $v }}"
          {{- end }}
          {{- end }}
          command: ["/entrypoint.sh", pelican-server, cache, serve]
          #command: ["sleep","infinity"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: web-ui
              containerPort: {{ .Values.service.ports.webui }}
            - name: xrootd
              containerPort: {{ .Values.service.ports.xrootd }}
          volumeMounts:
            - name: pelican-etc
              mountPath: /etc/pelican
            - name: pelican-lib
              mountPath: /var/lib/pelican
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: pelican-etc
          persistentVolumeClaim:
            claimName: pelican-config
        - name: pelican-lib
          persistentVolumeClaim:
            claimName: pelican-lib
