apiVersion: v1
kind: Service
metadata:
  name: pelican-xrootd
  labels:
    {{- include "pelican-cache.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: {{ include "pelican-cache.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: xrootd
      port: {{ .Values.service.ports.xrootd }}
      targetPort: xrootd
      protocol: TCP
      {{- if .Values.service.xrootdNodePort }}
      nodePort: {{ .Values.service.xrootdNodePort }}
      {{- end }}
