{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "pelican-cache.fullname" . }}-web-ui
  labels:
    {{- include "pelican-cache.labels" . | nindent 4 }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host | quote }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "pelican-cache.fullname" . }}
  port:
    targetPort: web-ui
  tls:
    termination: {{ .Values.route.termination }}
    destinationCACertificate: |
      -----BEGIN CERTIFICATE-----
      MIIDUTCCAjmgAwIBAgIIV0Bjc6MZ83MwDQYJKoZIhvcNAQELBQAwNjE0MDIGA1UE
      Awwrb3BlbnNoaWZ0LXNlcnZpY2Utc2VydmluZy1zaWduZXJAMTU4MDI0NTExMjAe
      Fw0yNDA3MTAxNzQ0MzhaFw0yNjA5MDgxNzUwMzlaMDYxNDAyBgNVBAMMK29wZW5z
      aGlmdC1zZXJ2aWNlLXNlcnZpbmctc2lnbmVyQDE1ODAyNDUxMTIwggEiMA0GCSqG
      SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCvyNupxbDTQk+dNKRgVyCKTJ2I3Po5BEoX
      4Bc8zycpFiedlrkw/Dtj+l3o7PB+5B8RVDPUuKAG2KrD8gIMp8X57B49EeLPIzfm
      E0uQ9PfFnbdKyVtXPjoScyomfpPjj8ik7XbEDIYXm1q3BTl30TYGzoLwyKTKyqDB
      OlNAY26cYa0E9hJiy4OFPO8UPZCa9+P2VQgx+fGv+im21e5nQaxIX3RbKprNuCet
      +G9chrsUgwu3T5+vZfknk6/PedgLLh+P6EgoLm76FX/fcc9SXoV4vOc097xlNkGi
      O7SC5ULwuAvhCWc2oIaY7RI8bZMBOiFe3AhpQRbY6rx4BJ17yZVJAgMBAAGjYzBh
      MA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQDYHB6
      fll40uiWHvY4MgavlHDJIjAfBgNVHSMEGDAWgBTymFNSOS8nhIEHy/HDS8z1kZZe
      /jANBgkqhkiG9w0BAQsFAAOCAQEAP8SHtXOdYI+IynlUK+EB+jbxzjcY8Pid+V74
      6bOzoZlRmnn+c1oaRdQz5aXt7QCNKlELh799wlMPxl2rHJ6lm7SS7Z/1ovXlfML/
      xSYJiMDPz6ygEmNKwSeSIv2KfyT9YKbojShwqBgwN5YLqh+pkF2IGUCRCjW4lRlN
      awn8ebNddUmMD8YWF7S57eOiMDuU4ycSvQ9/gAOY568hh9u04pK8xc/aUnpVRCwg
      /bQQ9fsB9Ewtfs65NAESNYt3XExwvwV4sq4DahvuoOhwjzMW4ilLJUXbXG3d3d7/
      5hq+Fib85OXThLEMWr1nEKGSXWtzrBUU2D+BTxyQn6Wr73aU6w==
      -----END CERTIFICATE-----
{{- end }}
