apiVersion: v1
kind: Service
metadata:
  name: pelican
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: pelican-cache-tls

  labels:
    {{- include "pelican-cache.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "pelican-cache.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: web-ui
      port: {{ .Values.service.ports.webui }}
      targetPort: web-ui
      protocol: TCP
    - name: xrootd
      port: {{ .Values.service.ports.xrootd }}
      targetPort: xrootd
      protocol: TCP
